- include: osx.yml
  when: ansible_os_family == "Darwin"

- include: debian.yml
  when: ansible_os_family == "Debian"

# TODO: Fedora installation

- name: Install common npm utilities
  npm: name={{item}} state=present global=yes
  with_items: npm_global_packages
