- include: osx.yml
  when: ansible_os_family == "Darwin"

# TODO: Fedora and debian installation

- name: Install common npm utilities
  npm: name={{item}} state=present global=yes
  with_items: npm_global_packages
