# Installation
- include: debian.yml
  when: ansible_os_family == "Debian"
- include: redhat.yml
  when: ansible_os_family == "RedHat"
- include: osx.yml
  when: ansible_os_family == "Darwin"

# Plugin manager
# - name: Install Vundle
#   git: repo=https://github.com/gmarik/Vundle.vim.git
#        dest=~/.vim/bundle/Vundle.vim
#        update=no

- name: Makes sure autoload directory exists
  file: path="{{dotfiles_user_home}}/.vim/autoload" state=directory

- name: Install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: "{{dotfiles_user_home}}/.vim/autoload/plug.vim"

# Configuration
- name: Makes sure snippets directory exists
  file: path="{{dotfiles_user_home}}/.vim/snippets" state=directory

- name: Copy all snippet files
  copy: src={{ item }} dest={{ dotfiles_user_home + '/.vim/snippets/' + item }}
  with_items:
    - "_.snippets"
    - "python.snippets"
    - "rst.snippets"

- name: Check if vimrc exists
  stat: path="{{dotfiles_user_home}}/.vimrc"
  register: vimrc_stat
  failed_when: False

- name: Backup vimrc
  command: mv ~/.vimrc ~/.vimrc.bak
  args:
    creates: "{{dotfiles_user_home}}/.vimrc.bak"
  when: vimrc_stat.stat.exists

- name: Symlink vimrc
  file:
    src: "{{ dotfiles_home }}/roles/vim/files/vimrc"
    dest: "{{dotfiles_user_home}}/.vimrc"
    state: link
  when: not vim_minimal

- name: Symlink minimal vimrc
  file:
    src: "{{ dotfiles_home }}/roles/vim/files/vimrc_minimal"
    dest: "{{dotfiles_user_home}}/.vimrc"
    state: link
  when: vim_minimal

- name: Install plugins
  command: vim +PlugInstall +qall
  when: vim_install_plugins
